export const FETCH_ROOMS_START = 'FETCH_ROOMS_START';
export const FETCH_ROOMS_SUCCESS = 'FETCH_ROOMS_SUCCESS';
export const FETCH_ROOMS_ERROR = 'FETCH_ROOMS_ERROR';

export const FETCH_PARTIAL_ROOMS_START = 'FETCH_PARTIAL_ROOMS_START';
export const FETCH_PARTIAL_ROOMS_SUCCESS = 'FETCH_PARTIAL_ROOMS_SUCCESS';
export const FETCH_PARTIAL_ROOMS_ERROR = 'FETCH_PARTIAL_ROOMS_ERROR';

export const CREATE_ROOM_START = 'CREATE_ROOM_START';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const CREATE_ROOM_ERROR = 'CREATE_ROOM_ERROR';

export const DELETE_ROOM_START = 'DELETE_ROOM_START';
export const DELETE_ROOM_SUCCESS = 'DELETE_ROOM_SUCCESS';
export const DELETE_ROOM_ERROR = 'DELETE_ROOM_ERROR';
