export const ADD_BET = 'ADD_BET';

export const FETCH_ROUND_START = 'FETCH_ROUND_START';
export const FETCH_ROUND_ERROR = 'FETCH_ROUND_ERROR';
export const FETCH_ROUND_SUCCESS = 'FETCH_ROUND_SUCCESS';

export const REFRESH_HISTORY = 'REFRESH_HISTORY';
export const ADD_TO_HISTORY = 'ADD_TO_HISTORY';

export const JOIN_ROULETTE = 'JOIN_ROULETTE';
export const START_ROLL = 'START_ROLL';
export const FINISH_ROLL = 'FINISH_ROLL';
export const START_ROUND = 'START_ROUND';
export const FINISH_ROUND = 'FINISH_ROUND';
